services:
  database:
    image: postgres:13
    container_name: springboot-essentials-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: spring_boot_essentials
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672